name: "Cache all flake outputs for each compatible system."

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v3
    - uses: cachix/install-nix-action@v30
      with:
        extra_nix_config: "extra-platforms = aarch64-linux"
    - uses: cachix/cachix-action@v15
      with:
        name: quinneden
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: |
        nix flake show --json --all-systems | \
          jq -r '"packages" as $top | .[$top] |
                 to_entries[] | .key as $arch |
                 .value | keys[] |
                 ".#\($top).\($arch).\(.)"' | \
          nix build --stdin
